// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.0
// source: grpc.proto

package worker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Trx struct {
	Key           string `json:"key"`
	Payload       string `json:"payload"`
	UserId        string `json:"userId"`
	MachineId     string `json:"machineId"`
	Runtime       string `json:"runtime"`
	CallbackId    string `json:"callbackId"`
}

func (x *Trx) Reset() {
	*x = Trx{}
	mi := &file_grpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trx) ProtoMessage() {}

func (x *Trx) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trx.ProtoReflect.Descriptor instead.
func (*Trx) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *Trx) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Trx) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *Trx) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Trx) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

type ExecTrxsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trxs          []*Trx                 `protobuf:"bytes,1,rep,name=trxs,proto3" json:"trxs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecTrxsRequest) Reset() {
	*x = ExecTrxsRequest{}
	mi := &file_grpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecTrxsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecTrxsRequest) ProtoMessage() {}

func (x *ExecTrxsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecTrxsRequest.ProtoReflect.Descriptor instead.
func (*ExecTrxsRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *ExecTrxsRequest) GetTrxs() []*Trx {
	if x != nil {
		return x.Trxs
	}
	return nil
}

type ExecTrxsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecTrxsReply) Reset() {
	*x = ExecTrxsReply{}
	mi := &file_grpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecTrxsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecTrxsReply) ProtoMessage() {}

func (x *ExecTrxsReply) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecTrxsReply.ProtoReflect.Descriptor instead.
func (*ExecTrxsReply) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{2}
}

func (x *ExecTrxsReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_grpc_proto protoreflect.FileDescriptor

var file_grpc_proto_rawDesc = string([]byte{
	0x0a, 0x0a, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6b, 0x61,
	0x73, 0x70, 0x65, 0x72, 0x22, 0x67, 0x0a, 0x03, 0x54, 0x72, 0x78, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x18, 0x0a,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x22, 0x32, 0x0a,
	0x0f, 0x45, 0x78, 0x65, 0x63, 0x54, 0x72, 0x78, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1f, 0x0a, 0x04, 0x74, 0x72, 0x78, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x6b, 0x61, 0x73, 0x70, 0x65, 0x72, 0x2e, 0x54, 0x72, 0x78, 0x52, 0x04, 0x74, 0x72, 0x78,
	0x73, 0x22, 0x29, 0x0a, 0x0d, 0x45, 0x78, 0x65, 0x63, 0x54, 0x72, 0x78, 0x73, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0x48, 0x0a, 0x08,
	0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x72, 0x12, 0x3c, 0x0a, 0x08, 0x45, 0x78, 0x65, 0x63,
	0x54, 0x72, 0x78, 0x73, 0x12, 0x17, 0x2e, 0x6b, 0x61, 0x73, 0x70, 0x65, 0x72, 0x2e, 0x45, 0x78,
	0x65, 0x63, 0x54, 0x72, 0x78, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e,
	0x6b, 0x61, 0x73, 0x70, 0x65, 0x72, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x54, 0x72, 0x78, 0x73, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x31, 0x0a, 0x10, 0x69, 0x6f, 0x2e, 0x77, 0x6f, 0x72,
	0x6b, 0x65, 0x72, 0x2e, 0x6b, 0x61, 0x73, 0x70, 0x65, 0x72, 0x42, 0x06, 0x4b, 0x61, 0x73, 0x70,
	0x65, 0x72, 0x50, 0x01, 0x5a, 0x0d, 0x6b, 0x61, 0x73, 0x70, 0x65, 0x72, 0x2f, 0x77, 0x6f, 0x72,
	0x6b, 0x65, 0x72, 0xa2, 0x02, 0x03, 0x48, 0x4c, 0x57, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
})

var (
	file_grpc_proto_rawDescOnce sync.Once
	file_grpc_proto_rawDescData []byte
)

func file_grpc_proto_rawDescGZIP() []byte {
	file_grpc_proto_rawDescOnce.Do(func() {
		file_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_proto_rawDesc), len(file_grpc_proto_rawDesc)))
	})
	return file_grpc_proto_rawDescData
}

var file_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_grpc_proto_goTypes = []any{
	(*Trx)(nil),             // 0: kasper.Trx
	(*ExecTrxsRequest)(nil), // 1: kasper.ExecTrxsRequest
	(*ExecTrxsReply)(nil),   // 2: kasper.ExecTrxsReply
}
var file_grpc_proto_depIdxs = []int32{
	0, // 0: kasper.ExecTrxsRequest.trxs:type_name -> kasper.Trx
	1, // 1: kasper.Executer.ExecTrxs:input_type -> kasper.ExecTrxsRequest
	2, // 2: kasper.Executer.ExecTrxs:output_type -> kasper.ExecTrxsReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpc_proto_init() }
func file_grpc_proto_init() {
	if File_grpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_proto_rawDesc), len(file_grpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_proto_goTypes,
		DependencyIndexes: file_grpc_proto_depIdxs,
		MessageInfos:      file_grpc_proto_msgTypes,
	}.Build()
	File_grpc_proto = out.File
	file_grpc_proto_goTypes = nil
	file_grpc_proto_depIdxs = nil
}
